/**
 * POST /api/gift-order — Create Printful order + Stripe checkout for personalized gifts
 *
 * Flow:
 * 1. Validate order details
 * 2. Create draft Printful order with a design mockup URL
 * 3. Create Stripe Checkout Session for payment
 * 4. Return checkout URL
 * 5. Printful order stays as draft until payment confirmed via webhook
 */

// Printful verified variant IDs
const PRINTFUL_VARIANTS = {
    mug:    { variant_id: 1320, name: 'White Glossy Mug 11oz' },
    poster: { variant_id: 3876, name: 'Enhanced Matte Poster 12×18"' },
    tshirt: { variant_id: 4012, name: 'Bella+Canvas 3001 White M' },
    tote:   { variant_id: 10458, name: 'Eco Tote Bag Oyster' },
    canvas: { variant_id: 19296, name: 'Canvas 10×10"' }
};

const TSHIRT_SIZES = { 'S': 4011, 'M': 4012, 'L': 4013, 'XL': 4014, '2XL': 4015 };

const GIFT_PRICES = {
    mug: 2200, poster: 2800, tshirt: 2800, tote: 2000, canvas: 3500
};

// Design is generated by /api/gift-design endpoint (public URL for Printful to fetch)

export async function onRequestPost(context) {
    const PRINTFUL_TOKEN = context.env.PRINTFUL_API_TOKEN;
    const STRIPE_KEY = context.env.STRIPE_SECRET_KEY;

    if (!STRIPE_KEY) {
        return Response.json({ error: 'Gift store coming soon' }, { status: 503 });
    }

    let body;
    try {
        body = await context.request.json();
    } catch {
        return Response.json({ error: 'Invalid request body' }, { status: 400 });
    }

    const { productType, milestoneValue, milestoneUnit, milestoneName,
            personalMessage, customerEmail, shippingAddress, size } = body;

    if (!productType || !GIFT_PRICES[productType]) {
        return Response.json({ error: 'Invalid product type' }, { status: 400 });
    }
    if (!milestoneValue || !milestoneUnit) {
        return Response.json({ error: 'Milestone value and unit are required' }, { status: 400 });
    }
    if (!customerEmail || !customerEmail.includes('@')) {
        return Response.json({ error: 'Valid email is required' }, { status: 400 });
    }
    if (!shippingAddress || !shippingAddress.name || !shippingAddress.address1 ||
        !shippingAddress.city || !shippingAddress.country_code || !shippingAddress.zip) {
        return Response.json({ error: 'Complete shipping address is required' }, { status: 400 });
    }

    const variant = PRINTFUL_VARIANTS[productType];
    const priceInCents = GIFT_PRICES[productType];
    const orderId = `hm-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;

    // Resolve t-shirt size
    let variantId = variant.variant_id;
    if (productType === 'tshirt' && size && TSHIRT_SIZES[size]) {
        variantId = TSHIRT_SIZES[size];
    }

    try {
        // Build a PUBLIC URL for the design image — Printful will fetch it
        const appUrl = context.env.APP_URL || 'https://happymoments.app';
        const designParams = new URLSearchParams({
            value: String(milestoneValue),
            unit: milestoneUnit,
            name: milestoneName || '',
            message: personalMessage || '',
            type: productType
        });
        const designUrl = `${appUrl}/api/gift-order?${designParams.toString()}`;

        // Create Printful order if token available
        let printfulOrderId = null;
        if (PRINTFUL_TOKEN) {
            try {

                // Create draft order — design will be added via Printful dashboard
                // (Cloudflare Pages doesn't reliably serve GET endpoints for new function files)
                const orderBody = {
                    external_id: orderId,
                    recipient: {
                        name: shippingAddress.name,
                        email: customerEmail,
                        address1: shippingAddress.address1,
                        city: shippingAddress.city,
                        country_code: shippingAddress.country_code,
                        zip: shippingAddress.zip
                    },
                    items: [{
                        variant_id: variantId,
                        quantity: 1,
                        name: `HappyMoments ${variant.name} — ${milestoneValue} ${milestoneUnit}` +
                              (milestoneName ? ` for ${milestoneName}` : '') +
                              (personalMessage ? ` "${personalMessage}"` : ''),
                        retail_price: (priceInCents / 100).toFixed(2)
                    }]
                };

                const orderResponse = await fetch('https://api.printful.com/orders', {
                    method: 'POST',
                    headers: {
                        'Authorization': `Bearer ${PRINTFUL_TOKEN}`,
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify(orderBody)
                });

                if (orderResponse.ok) {
                    const orderResult = await orderResponse.json();
                    if (orderResult.code === 200) {
                        printfulOrderId = orderResult.result.id;
                    }
                }
            } catch (pfErr) {
                // Printful failed — continue with Stripe-only checkout
                console.error('Printful error (non-blocking):', pfErr.message);
            }
        }

        // Create Stripe Checkout Session
        const appUrl = context.env.APP_URL || 'https://happymoments.app';
        const description = `Personalized: ${milestoneValue} ${milestoneUnit}` +
            (milestoneName ? ` for ${milestoneName}` : '') +
            (personalMessage ? ` — "${personalMessage}"` : '') +
            (size ? ` (${size})` : '');

        const stripeParams = new URLSearchParams({
            'mode': 'payment',
            'line_items[0][price_data][currency]': 'eur',
            'line_items[0][price_data][unit_amount]': String(priceInCents),
            'line_items[0][price_data][product_data][name]': `HappyMoments ${variant.name}`,
            'line_items[0][price_data][product_data][description]': description,
            'line_items[0][quantity]': '1',
            'success_url': `${appUrl}/index.html?checkout=gift_success&order=${orderId}`,
            'cancel_url': `${appUrl}/index.html?checkout=gift_cancelled`,
            'customer_email': customerEmail,
            'metadata[type]': 'gift',
            'metadata[order_id]': orderId,
            'metadata[printful_order_id]': String(printfulOrderId || 'pending'),
            'metadata[product]': productType,
            'metadata[milestone]': `${milestoneValue} ${milestoneUnit}`,
            'metadata[recipient]': milestoneName || '',
            'metadata[shipping]': `${shippingAddress.name}, ${shippingAddress.address1}, ${shippingAddress.city}, ${shippingAddress.country_code} ${shippingAddress.zip}`
        });

        const stripeResponse = await fetch('https://api.stripe.com/v1/checkout/sessions', {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${STRIPE_KEY}`,
                'Content-Type': 'application/x-www-form-urlencoded'
            },
            body: stripeParams.toString()
        });

        const session = await stripeResponse.json();
        if (session.error) {
            return Response.json({ error: 'Payment setup failed', detail: session.error.message }, { status: 502 });
        }

        return Response.json({
            checkoutUrl: session.url,
            sessionId: session.id,
            orderId: orderId,
            printfulOrderId: printfulOrderId
        });

    } catch (err) {
        return Response.json({ error: 'Order failed', detail: err.message }, { status: 500 });
    }
}

/**
 * GET /api/gift-order?value=10000&unit=days&name=Anna&type=mug
 * Serves the design SVG image for Printful to download.
 */
export async function onRequestGet(context) {
    const url = new URL(context.request.url);
    const value = url.searchParams.get('value') || '10000';
    const unit = url.searchParams.get('unit') || 'days';
    const name = url.searchParams.get('name') || '';
    const message = url.searchParams.get('message') || '';
    const type = url.searchParams.get('type') || 'mug';

    const sizes = {
        mug: { w: 2700, h: 1100 }, poster: { w: 3600, h: 5400 },
        tshirt: { w: 4500, h: 5400 }, tote: { w: 3600, h: 3600 }, canvas: { w: 3000, h: 3000 }
    };
    const dims = sizes[type] || sizes.mug;
    const W = dims.w, H = dims.h;
    const esc = (s) => String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
    const val = Number(value) ? Number(value).toLocaleString('en-US') : value;
    const numLen = val.replace(/,/g,'').length;
    const fontSize = numLen > 9 ? Math.floor(H*0.12) : numLen > 6 ? Math.floor(H*0.16) : Math.floor(H*0.22);

    const svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">
<rect width="${W}" height="${H}" fill="#1a1a1a"/>
<rect x="30" y="30" width="${W-60}" height="${H-60}" fill="none" stroke="#d4b876" stroke-width="2" opacity="0.2" rx="8"/>
<text x="${W/2}" y="${Math.floor(H*0.12)}" text-anchor="middle" font-family="Georgia,serif" font-size="${Math.floor(H*0.035)}" fill="#888" font-style="italic">HappyMoments</text>
${name ? `<text x="${W/2}" y="${type==='mug'?'30%':'28%'}" text-anchor="middle" font-family="Georgia,serif" font-size="${Math.floor(H*0.05)}" fill="#a0b8a0" font-style="italic">${esc(name)}</text>` : ''}
<text x="${W/2}" y="${type==='mug'?'55%':'50%'}" text-anchor="middle" font-family="Courier New,monospace" font-size="${fontSize}" fill="#d4b876" font-weight="300">${esc(val)}</text>
<text x="${W/2}" y="${type==='mug'?'70%':'60%'}" text-anchor="middle" font-family="Georgia,serif" font-size="${Math.floor(H*0.06)}" fill="#e0e0e0" font-style="italic">${esc(unit)}</text>
${message ? `<text x="${W/2}" y="${type==='mug'?'82%':'72%'}" text-anchor="middle" font-family="Georgia,serif" font-size="${Math.floor(H*0.04)}" fill="#888" font-style="italic">${esc(message)}</text>` : ''}
<text x="${W/2}" y="${type==='mug'?'95%':'92%'}" text-anchor="middle" font-family="Georgia,serif" font-size="${Math.floor(H*0.025)}" fill="#888">happymoments.app</text>
</svg>`;

    return new Response(svg, {
        headers: { 'Content-Type': 'image/svg+xml', 'Cache-Control': 'public, max-age=86400', 'Access-Control-Allow-Origin': '*' }
    });
}
