/**
 * POST /api/gift-order — Create Printful order + Stripe checkout for personalized gifts
 *
 * Flow:
 * 1. Validate order details
 * 2. Create draft Printful order with a design mockup URL
 * 3. Create Stripe Checkout Session for payment
 * 4. Return checkout URL
 * 5. Printful order stays as draft until payment confirmed via webhook
 */

// Printful verified variant IDs (live-catalog confirmed)
const PRINTFUL_VARIANTS = {
    mug:     { variant_id: 1320,  name: 'White Glossy Mug 11oz' },
    tshirt:  { variant_id: 4012,  name: 'Bella+Canvas 3001 White M' },
    tumbler: { variant_id: 19111, name: 'Insulated Tumbler with a Straw (White / 20 oz)' }
};

const TSHIRT_SIZES = { 'S': 4011, 'M': 4012, 'L': 4013, 'XL': 4014, '2XL': 4015 };

// Retail charged to the customer (cents, EUR, VAT-inclusive). Shipping is included
// in this price — Printful bills wholesale+shipping to the merchant; margin covers it.
const GIFT_PRICES = {
    mug: 2200, tshirt: 2800, tumbler: 4400
};

// Design is generated by /api/gift-design endpoint (public URL for Printful to fetch)

export async function onRequestPost(context) {
    const PRINTFUL_TOKEN = context.env.PRINTFUL_API_TOKEN;
    const STRIPE_KEY = context.env.STRIPE_SECRET_KEY;

    if (!STRIPE_KEY) {
        return Response.json({ error: 'Gift store coming soon' }, { status: 503 });
    }

    let body;
    try {
        body = await context.request.json();
    } catch {
        return Response.json({ error: 'Invalid request body' }, { status: 400 });
    }

    const { productType, milestoneValue, milestoneUnit, milestoneName,
            personalMessage, customerEmail, shippingAddress, size, designImage,
            customLine, numberText, unitText } = body;

    if (!productType || !GIFT_PRICES[productType]) {
        return Response.json({ error: 'Invalid product type' }, { status: 400 });
    }
    if (!milestoneValue || !milestoneUnit) {
        return Response.json({ error: 'Milestone value and unit are required' }, { status: 400 });
    }
    if (!customerEmail || !customerEmail.includes('@')) {
        return Response.json({ error: 'Valid email is required' }, { status: 400 });
    }
    if (!shippingAddress || !shippingAddress.name || !shippingAddress.address1 ||
        !shippingAddress.city || !shippingAddress.country_code || !shippingAddress.zip) {
        return Response.json({ error: 'Complete shipping address is required' }, { status: 400 });
    }

    const variant = PRINTFUL_VARIANTS[productType];
    const priceInCents = GIFT_PRICES[productType];
    const orderId = `hm-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;

    // Resolve t-shirt size
    let variantId = variant.variant_id;
    if (productType === 'tshirt' && size && TSHIRT_SIZES[size]) {
        variantId = TSHIRT_SIZES[size];
    }

    try {
        // Build a PUBLIC URL for the design image — Printful will fetch it
        const appUrl = context.env.APP_URL || 'https://nicenumbers.app';
        const designParams = new URLSearchParams({
            value: String(milestoneValue),
            unit: (unitText || milestoneUnit),
            name: milestoneName || '',
            message: personalMessage || '',
            custom: customLine || '',
            number: numberText || '',
            type: productType
        });
        // Print file URL that Printful will fetch.
        // Preferred: a client-rendered PNG (pixel-perfect, correct fonts) stored in D1
        // and served as a raster — Printful renders rasters reliably. The server SVG
        // endpoint is only a fallback (live-text SVG can rasterize blank on Printful).
        let designUrl = `${appUrl}/api/gift-design?${designParams.toString()}`;

        if (designImage && context.env.DB) {
            try {
                const b64 = String(designImage).replace(/^data:image\/[a-z]+;base64,/, '');
                // D1 rejects values over 2 MB — keep a safe margin (base64 ≈ 1.33× bytes).
                if (b64.length > 40 && b64.length < 1_900_000) {
                    await context.env.DB.prepare(
                        'CREATE TABLE IF NOT EXISTS gift_files (id TEXT PRIMARY KEY, data TEXT NOT NULL, created INTEGER)'
                    ).run();
                    await context.env.DB.prepare(
                        'INSERT OR REPLACE INTO gift_files (id, data, created) VALUES (?, ?, ?)'
                    ).bind(orderId, b64, Date.now()).run();
                    designUrl = `${appUrl}/api/gift-file?id=${encodeURIComponent(orderId)}`;
                }
            } catch {
                // keep SVG fallback designUrl
            }
        }

        // Create Printful order if token available
        let printfulOrderId = null;
        if (PRINTFUL_TOKEN) {
            try {

                // Create draft order with the personalized per-number design
                const orderBody = {
                    external_id: orderId,
                    recipient: {
                        name: shippingAddress.name,
                        email: customerEmail,
                        address1: shippingAddress.address1,
                        city: shippingAddress.city,
                        country_code: shippingAddress.country_code,
                        // Printful requires state_code for US/CA/AU/JP/BR; omitted
                        // (undefined → dropped by JSON) for countries without states.
                        state_code: shippingAddress.state_code || undefined,
                        zip: shippingAddress.zip
                    },
                    items: [{
                        variant_id: variantId,
                        quantity: 1,
                        name: `Nice Numbers ${variant.name} — ${milestoneValue} ${milestoneUnit}` +
                              (milestoneName ? ` for ${milestoneName}` : '') +
                              (personalMessage ? ` "${personalMessage}"` : ''),
                        retail_price: (priceInCents / 100).toFixed(2),
                        files: [{ type: 'default', url: designUrl }]
                    }]
                };

                const orderResponse = await fetch('https://api.printful.com/orders', {
                    method: 'POST',
                    headers: {
                        'Authorization': `Bearer ${PRINTFUL_TOKEN}`,
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify(orderBody)
                });

                const orderResult = await orderResponse.json();
                if (orderResponse.ok && orderResult.code === 200) {
                    printfulOrderId = orderResult.result.id;
                } else {
                    // Store error for debugging (temporary)
                    printfulOrderId = 'ERROR: ' + JSON.stringify(orderResult).substring(0, 200);
                }
            } catch (pfErr) {
                printfulOrderId = 'EXCEPTION: ' + pfErr.message;
            }
        }

        // Create Stripe Checkout Session
        const description = `Personalized: ${milestoneValue} ${milestoneUnit}` +
            (milestoneName ? ` for ${milestoneName}` : '') +
            (personalMessage ? ` — "${personalMessage}"` : '') +
            (size ? ` (${size})` : '');

        const stripeParams = new URLSearchParams({
            'mode': 'payment',
            // Card only — keep checkout simple and predictable (no Bancontact/EPS/
            // Satispay/MB WAY). Matches the premium checkout.
            'payment_method_types[0]': 'card',
            'line_items[0][price_data][currency]': 'eur',
            'line_items[0][price_data][unit_amount]': String(priceInCents),
            'line_items[0][price_data][product_data][name]': `Nice Numbers ${variant.name}`,
            'line_items[0][price_data][product_data][description]': description,
            'line_items[0][quantity]': '1',
            'success_url': `${appUrl}/index.html?checkout=gift_success&order=${orderId}`,
            'cancel_url': `${appUrl}/index.html?checkout=gift_cancelled`,
            'customer_email': customerEmail,
            'metadata[type]': 'gift',
            'metadata[order_id]': orderId,
            'metadata[printful_order_id]': String(printfulOrderId || 'pending'),
            'metadata[product]': productType,
            'metadata[milestone]': `${milestoneValue} ${milestoneUnit}`,
            'metadata[recipient]': milestoneName || '',
            'metadata[shipping]': `${shippingAddress.name}, ${shippingAddress.address1}, ${shippingAddress.city}, ${shippingAddress.country_code} ${shippingAddress.zip}`
        });

        const stripeResponse = await fetch('https://api.stripe.com/v1/checkout/sessions', {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${STRIPE_KEY}`,
                'Content-Type': 'application/x-www-form-urlencoded'
            },
            body: stripeParams.toString()
        });

        const session = await stripeResponse.json();
        if (session.error) {
            return Response.json({ error: 'Payment setup failed', detail: session.error.message }, { status: 502 });
        }

        return Response.json({
            checkoutUrl: session.url,
            sessionId: session.id,
            orderId: orderId,
            printfulOrderId: printfulOrderId
        });

    } catch (err) {
        return Response.json({ error: 'Order failed', detail: err.message }, { status: 500 });
    }
}

/**
 * GET /api/gift-order?value=10000&unit=days&name=Anna&type=mug
 * Serves the design SVG image for Printful to download.
 */
export async function onRequestGet(context) {
    const url = new URL(context.request.url);
    const value = url.searchParams.get('value') || '10000';
    const unit = url.searchParams.get('unit') || 'days';
    const name = url.searchParams.get('name') || '';
    const message = url.searchParams.get('message') || '';
    const custom = url.searchParams.get('custom') || '';
    const numberText = url.searchParams.get('number') || '';
    const type = url.searchParams.get('type') || 'mug';

    const sizes = {
        mug: { w: 2700, h: 1100 }, tshirt: { w: 4500, h: 5400 }, tumbler: { w: 3017, h: 1200 }
    };
    const dims = sizes[type] || sizes.mug;
    const wide = (type === 'mug' || type === 'tumbler'); // horizontal wrap layout
    const W = dims.w, H = dims.h;
    const esc = (s) => String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
    // Match the client's formatMilestoneValue: abbreviate only clean round
    // millions/billions, keep everything else exact — so this fallback never
    // shows a different number than the app/card preview.
    const fmtVal = (n) => {
        if (n >= 1000000 && n % 100000 === 0) {
            if (n >= 1000000000) { const b = n / 1000000000; return (Number.isInteger(b) ? b : parseFloat(b.toFixed(2))).toLocaleString('en-US') + ' billion'; }
            const m = n / 1000000; return (Number.isInteger(m) ? m : parseFloat(m.toFixed(1))).toLocaleString('en-US') + ' million';
        }
        return n.toLocaleString('en-US');
    };
    const val = numberText ? numberText : (Number(value) ? fmtVal(Number(value)) : value);
    const numLen = val.replace(/[,\s]/g,'').length;
    const fontSize = numLen > 9 ? Math.floor(H*0.12) : numLen > 6 ? Math.floor(H*0.16) : Math.floor(H*0.22);

    const svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">
<rect width="${W}" height="${H}" fill="#1a1a1a"/>
<rect x="30" y="30" width="${W-60}" height="${H-60}" fill="none" stroke="#d4b876" stroke-width="2" opacity="0.2" rx="8"/>
<text x="${W/2}" y="${Math.floor(H*0.12)}" text-anchor="middle" font-family="Georgia,serif" font-size="${Math.floor(H*0.035)}" fill="#888" font-style="italic">Nice Numbers</text>
${name ? `<text x="${W/2}" y="${wide?'30%':'28%'}" text-anchor="middle" font-family="Georgia,serif" font-size="${Math.floor(H*0.05)}" fill="#a0b8a0" font-style="italic">${esc(name)}</text>` : ''}
<text x="${W/2}" y="${wide?'55%':'50%'}" text-anchor="middle" font-family="Courier New,monospace" font-size="${fontSize}" fill="#d4b876" font-weight="300">${esc(val)}</text>
<text x="${W/2}" y="${wide?'70%':'60%'}" text-anchor="middle" font-family="Georgia,serif" font-size="${Math.floor(H*0.06)}" fill="#e0e0e0" font-style="italic">${esc(unit)}</text>
${message ? `<text x="${W/2}" y="${wide?'82%':'72%'}" text-anchor="middle" font-family="Georgia,serif" font-size="${Math.floor(H*0.04)}" fill="#888" font-style="italic">${esc(message)}</text>` : ''}
${custom ? `<text x="${W/2}" y="${wide?'95%':'90%'}" text-anchor="middle" font-family="Georgia,serif" font-size="${Math.floor(H*0.04)}" fill="#e0e0e0" font-style="italic">${esc(custom)}</text>` : ''}
</svg>`;

    return new Response(svg, {
        headers: { 'Content-Type': 'image/svg+xml', 'Cache-Control': 'public, max-age=86400', 'Access-Control-Allow-Origin': '*' }
    });
}
